SDT-95(ordinario): validacion de egresado no pueda cambiar calificaciones
cetherdev/siiges pull request #101
Opened 2023-02-23 18:55 UTC by joe2141

creo que hay un  error en esta parte del codigo pero lo dejo a tu revision 
![image](https://user-images.githubusercontent.com/57415186/221003509-72f69ee7-9c8b-42db-9b70-6c5d4c6f3d9a.png)

2023-03-09 05:18 UTC, robertotorres-dev requested changes

2023-03-09 05:18 UTC, robertotorres-dev commented on views/ce-ordinarios.php
>  												<td><?php echo $resultadoPersona["data"]["apellido_paterno"] . " " . $resultadoPersona["data"]["apellido_materno"] . " " . $resultadoPersona["data"]["nombre"]; ?></td>
Es lo único que no me cuadra en el código, quitaste la impresión de la matrícula, y pusiste un valor random?

2023-03-09 18:59 UTC, joe2141 commented on views/ce-ordinarios.php
>  												<td><?php echo $resultadoPersona["data"]["apellido_paterno"] . " " . $resultadoPersona["data"]["apellido_materno"] . " " . $resultadoPersona["data"]["nombre"]; ?></td>
Listo ya lo cheque y esta resuelto

2023-03-14 15:29 UTC, robertotorres-dev approved these changes

2023-03-14 15:32 UTC, Lau1980 approved these changes

2023-03-14 15:32 UTC, merged